### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by voutasaurus**
Signed-off-by: Anthony Voutas <anthonyv@kiva.org>

### CODE REVIEW

**Comment by voutasaurus** [comment]
@jsaur your thoughts on this latest error would be appreciated. I tried reverting crypto-random-string to 3.3.1 but the error persisted so it might be caused by the jest update, not sure

**Comment by jsaur** [comment]
Ya, I'm seeing the same thing... want about reverting jest to an earlier build? (or does it have security issues?)
The other option I'm seeing is potentially to use babel-jest to do the transforms instead of ts-jest
https://stackoverflow.com/questions/59879689/jest-syntaxerror-cannot-use-import-statement-outside-a-module
This would require adding a new dev module and a babel config, etc...

**Comment by voutasaurus** [comment]
I just reverted all the jest related dependencies and the error is still occuring

**Comment by voutasaurus** [comment]
Might need to go with the babel-jest option

**Pull request closed without merging**
